apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: bHB1cmxzdXNlcg==
  MYSQL_PASSWORD: bHB1cmxzcGFzc3dk
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: bHB1cmxzcGFzc3dk
